/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iccr.poo.ej1.gui;

import iccr.poo.ej1.Conejo;
import iccr.poo.ej1.Veterinario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LabP4109
 */
public class FrmConejo extends javax.swing.JFrame {

    Conejo c;
    Veterinario veterinario;
    final int TAMANIO_ARREGLOS;
    Conejo conejos[];
    int contador;
    //tabla
    DefaultTableModel dtmModelo;

    /**
     * Creates new form FrmConejo
     */
    public FrmConejo() {
        initComponents();
        //instancia para crear la tabla
        dtmModelo = new DefaultTableModel();
        //columnas de la tabla
        dtmModelo.addColumn("Nombre");
        dtmModelo.addColumn("Peso");
        dtmModelo.addColumn("Edad");
        tblConejos.setModel(dtmModelo);
        Conejo c2 = new Conejo(2, 0.2, 1, "lola");
        //lista inicializadora: conjunto de elementos que permite poblar un 
        //arreglo unidimensional o bimensinal ejm: int edades[]={1,2,3,4,5};

        dtmModelo.addRow(new Object[]{c2.getNombre(), c2.getPeso(), c2.getEdad()});

        veterinario = new Veterinario();
        btnDiagnosticar.setEnabled(false);
        btnGuardarDieta.setEnabled(false);
        btnNuevo.setEnabled(false);

        String nombreUsuario;
        nombreUsuario = JOptionPane.showInputDialog("Ingrese su nombre");
        JOptionPane.showMessageDialog(rootPane, "Bienvenido " + nombreUsuario);
        //arreglar
        String tam;
        tam = JOptionPane.showInputDialog(" # de conejos que quiere crear");
        TAMANIO_ARREGLOS = Integer.parseInt(tam);
        conejos = new Conejo[TAMANIO_ARREGLOS];

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btgSexo = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblEdad = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        lblTasaCrecimientoPorcentual = new javax.swing.JLabel();
        txtTasaCrecimientoPorcentual = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        cmbRaza = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkEsterilizado = new javax.swing.JCheckBox();
        rbtFemenino = new javax.swing.JRadioButton();
        rbtMasculino = new javax.swing.JRadioButton();
        lblDieta = new javax.swing.JLabel();
        chkAlfalfa = new javax.swing.JCheckBox();
        chkHeno = new javax.swing.JCheckBox();
        chkAlimentoProcesado = new javax.swing.JCheckBox();
        chkZanahoria = new javax.swing.JCheckBox();
        chkPlatano = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaResultado = new javax.swing.JTextArea();
        btnDiagnosticar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardarDieta = new javax.swing.JButton();
        tblConejo = new javax.swing.JScrollPane();
        tblConejos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Conejo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lblEdad.setText("Edad");

        lblPeso.setText("Peso");

        lblTasaCrecimientoPorcentual.setText("Tasa de Crecimiento Porcentual");

        lblNombre.setText("Nombre");

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la raza", "Angora", "California", "Habana", "Himalayo", "Rex" }));

        jLabel1.setText("Raza");

        jLabel2.setText("Sexo");

        chkEsterilizado.setText("Esterilizado");

        btgSexo.add(rbtFemenino);
        rbtFemenino.setText("Femenino");

        btgSexo.add(rbtMasculino);
        rbtMasculino.setText("Masculino");

        lblDieta.setText("Dieta");

        chkAlfalfa.setText("Alfalfa");

        chkHeno.setText("Heno");

        chkAlimentoProcesado.setText("Alimento Procesado");

        chkZanahoria.setText("Zanahoria");

        chkPlatano.setText("Platano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTasaCrecimientoPorcentual)
                            .addComponent(lblPeso)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkHeno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(chkAlfalfa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkZanahoria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(txtTasaCrecimientoPorcentual))
                            .addComponent(chkPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(chkAlimentoProcesado)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkEsterilizado)
                            .addComponent(txtNombre)
                            .addComponent(cmbRaza, 0, 163, Short.MAX_VALUE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtFemenino)
                            .addComponent(rbtMasculino))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeso)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(rbtFemenino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTasaCrecimientoPorcentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTasaCrecimientoPorcentual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkAlfalfa)
                            .addComponent(chkZanahoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chkEsterilizado)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDieta)
                            .addComponent(chkHeno)
                            .addComponent(chkPlatano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAlimentoProcesado)
                        .addGap(8, 8, 8))))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtaResultado.setColumns(20);
        txtaResultado.setRows(5);
        jScrollPane1.setViewportView(txtaResultado);

        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.setToolTipText("");
        btnDiagnosticar.setActionCommand("");
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardarDieta.setText("Guardar Dieta");
        btnGuardarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDietaActionPerformed(evt);
            }
        });

        tblConejos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConejo.setViewportView(tblConejos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(35, 35, 35)
                .addComponent(btnDiagnosticar)
                .addGap(38, 38, 38)
                .addComponent(btnNuevo)
                .addGap(38, 38, 38)
                .addComponent(btnGuardarDieta)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(tblConejo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnDiagnosticar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardarDieta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblConejo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            int edad = Integer.parseInt(txtEdad.getText());
            double peso = Double.parseDouble(txtPeso.getText());
            double tasaCrecimientoPorcentual = Double.parseDouble(txtTasaCrecimientoPorcentual.getText());
            String nombre = txtNombre.getText();

            c = new Conejo(edad, peso, tasaCrecimientoPorcentual, nombre);

            String raza = cmbRaza.getSelectedItem().toString();
            c.setRaza(raza);
            /* Asignar el valor de la variable sexo
        dependiendo de la selección del radio button
             */
            if (rbtFemenino.isSelected()) {
                c.setSexo("FEMENINO");
            }

            if (rbtMasculino.isSelected()) {
                c.setSexo(rbtMasculino.getText().toUpperCase());
            }

            /*
        asignar el valor de true en la variable estaEsterilizado
        cuando el check box se encuentre seleccionado
             */
            if (chkEsterilizado.isSelected()) {
                c.setEstaEsterilizado(true);
            }

            txtaResultado.append(c.toString() + "\n");
            //Colocar la instancia creada en el arreglo
            //utilizar un contador 
            conejos[contador] = c;
            contador++;
            agregarFila();

            //botones activados
            btnGuardarDieta.setEnabled(true);
            btnDiagnosticar.setEnabled(true);
            btnNuevo.setEnabled(true);

            JOptionPane.showMessageDialog(rootPane, "Conejo "
                    + "registrado exitosamente", "Informacion", 1);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Debe ingresar numeros "
                    + "en la edad, peso y tasa de crecimiento", "Error",
                    JOptionPane.ERROR_MESSAGE);

        } catch (ArrayIndexOutOfBoundsException aiobe) {
            JOptionPane.showMessageDialog(null, "El arreglo no puede "
                    + "guadar mas de " + TAMANIO_ARREGLOS + " elementos",
                    "Elementos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed


    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        // TODO add your handling code here:
        String diagnostico = veterinario.diagnosticar(c);
        txtaResultado.append(diagnostico);
        btnDiagnosticar.setEnabled(true);
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDietaActionPerformed
        // TODO add your handling code here:
        //alamacenar cada una de las opciones seleccionadas en una posicion del 
        //arreglo dieta
        String dietaSeleccionada[] = new String[5];
        if (chkAlfalfa.isSelected()) {
            dietaSeleccionada[0] = "Alfalfa";
        }

        if (chkHeno.isSelected()) {
            dietaSeleccionada[1] = chkHeno.getText();
        }

        if (chkAlimentoProcesado.isSelected()) {
            dietaSeleccionada[2] = chkAlimentoProcesado.getText();
        }

        if (chkZanahoria.isSelected()) {
            dietaSeleccionada[3] = chkZanahoria.getText();
        }

        if (chkPlatano.isSelected()) {
            dietaSeleccionada[4] = chkPlatano.getText();
        }

        c.setDieta(dietaSeleccionada);

        JOptionPane.showMessageDialog(rootPane, c.presentarDieta(),
                "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarDietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConejo().setVisible(true);
            }
        });
    }

    private void limpiarFormulario() {
        txtEdad.setText("");
        txtPeso.setText("");
        txtTasaCrecimientoPorcentual.setText("");
        txtNombre.setText("");
        cmbRaza.setSelectedIndex(0);
        btgSexo.clearSelection();
        chkEsterilizado.setSelected(false);
        chkAlfalfa.setSelected(false);
        chkHeno.setSelected(false);
        chkAlimentoProcesado.setSelected(false);
        chkZanahoria.setSelected(false);
        chkPlatano.setSelected(false);

    }

    /*metodo recorre todo el arreglo y colocar cada elemento*/
    private void llenarTabla() {
        /*colocar el nombre, peso y edad de cada elemento del arreglo 
        conejos en una fila de la tabla tblConejos
         */

        for (Conejo c : conejos) {
            dtmModelo.addRow(new Object[]{c.getNombre(), c.getPeso(), c.getEdad()});
        }
    }

    private void agregarFila() {
        dtmModelo.addRow(new Object[]{c.getNombre(), c.getPeso(), c.getEdad()});

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexo;
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarDieta;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkAlfalfa;
    private javax.swing.JCheckBox chkAlimentoProcesado;
    private javax.swing.JCheckBox chkEsterilizado;
    private javax.swing.JCheckBox chkHeno;
    private javax.swing.JCheckBox chkPlatano;
    private javax.swing.JCheckBox chkZanahoria;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDieta;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTasaCrecimientoPorcentual;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JScrollPane tblConejo;
    private javax.swing.JTable tblConejos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTasaCrecimientoPorcentual;
    private javax.swing.JTextArea txtaResultado;
    // End of variables declaration//GEN-END:variables
}
