/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iccr.poo.ej1.gui;

import iccr.poo.ej1.Conejo;
import iccr.poo.ej1.Gato;
import iccr.poo.ej1.Mascota;
import iccr.poo.ej1.Perro;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author LabP41010
 */
public class FrmMascotas extends javax.swing.JFrame {

    private ArrayList<Mascota> listaDeMascotas;
    String nombre;
    double peso;
    boolean estaEsterilizado;

    /**
     * Creates new form FrmMascotas
     */
    public FrmMascotas() {
        initComponents();
        listaDeMascotas = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        chkEstaEsterilizado = new javax.swing.JCheckBox();
        btnGuardarConejo = new javax.swing.JButton();
        btnGuardarPerro = new javax.swing.JButton();
        btnGuardarGato = new javax.swing.JButton();
        txtaInformacion = new javax.swing.JScrollPane();
        txtaResultado = new javax.swing.JTextArea();
        lblElementosDeLaLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        lblPeso.setText("Peso");

        chkEstaEsterilizado.setText("Esta Esterilizado");

        btnGuardarConejo.setText("Guardar Conejo");
        btnGuardarConejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConejoActionPerformed(evt);
            }
        });

        btnGuardarPerro.setText("Guardar Perro");
        btnGuardarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPerroActionPerformed(evt);
            }
        });

        btnGuardarGato.setText("Guardar Gato");
        btnGuardarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGatoActionPerformed(evt);
            }
        });

        txtaResultado.setColumns(20);
        txtaResultado.setRows(5);
        txtaInformacion.setViewportView(txtaResultado);

        lblElementosDeLaLista.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarConejo)
                        .addGap(13, 13, 13)
                        .addComponent(btnGuardarGato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarPerro))
                    .addComponent(chkEstaEsterilizado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtPeso))
                        .addGap(27, 27, 27)
                        .addComponent(lblElementosDeLaLista))
                    .addComponent(txtaInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblElementosDeLaLista)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkEstaEsterilizado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarConejo)
                    .addComponent(btnGuardarPerro)
                    .addComponent(btnGuardarGato))
                .addGap(18, 18, 18)
                .addComponent(txtaInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void obtenerDatosDeLaGUI() {
        try {
            //variables locales
            nombre = txtNombre.getText();
            peso = Double.parseDouble(txtPeso.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Error en el ingreso de datos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        estaEsterilizado = false;
        if (chkEstaEsterilizado.isSelected()) {
            estaEsterilizado = true;
        }
    }
    private void btnGuardarConejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConejoActionPerformed
        // TODO add your handling code here:
        //1.- tomar los datos d la GUI para crear un Conejo
        obtenerDatosDeLaGUI();
        //2.- Utilizar una instancia de conejo para crear un objeto
        Conejo c = new Conejo(nombre, peso, estaEsterilizado);
        //3.- agregar la intancia creada de la lista
        listaDeMascotas.add(c);
        presentarInformacion();
        lblElementosDeLaLista.setText("Elementos: " + listaDeMascotas.size());

    }//GEN-LAST:event_btnGuardarConejoActionPerformed

    private void btnGuardarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGatoActionPerformed
        // TODO add your handling code here:
        obtenerDatosDeLaGUI();
        listaDeMascotas.add(new Gato(nombre, peso, estaEsterilizado));
        presentarInformacion();
        lblElementosDeLaLista.setText("Elementos: " + listaDeMascotas.size());
    }//GEN-LAST:event_btnGuardarGatoActionPerformed

    private void btnGuardarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPerroActionPerformed
        // TODO add your handling code here:
        obtenerDatosDeLaGUI();
        listaDeMascotas.add(new Perro(nombre, peso, estaEsterilizado));
        presentarInformacion();
        lblElementosDeLaLista.setText("Elementos: " + listaDeMascotas.size());
    }//GEN-LAST:event_btnGuardarPerroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMascotas().setVisible(true);
            }
        });
    }

    private void presentarInformacion() {
        txtaResultado.setText("");
        for (Mascota m : listaDeMascotas) {
            m.presentarOnomatopeya();
            txtaResultado.append(m.getNombre() + " hace " + m.presentarOnomatopeya() + '\n');
            if (m instanceof Conejo) {
                Conejo c = (Conejo) m;
                txtaResultado.append(c.presentarCuidados());
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarConejo;
    private javax.swing.JButton btnGuardarGato;
    private javax.swing.JButton btnGuardarPerro;
    private javax.swing.JCheckBox chkEstaEsterilizado;
    private javax.swing.JLabel lblElementosDeLaLista;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JScrollPane txtaInformacion;
    private javax.swing.JTextArea txtaResultado;
    // End of variables declaration//GEN-END:variables
}
